### ISSUE TITLE
lua-bit32 

### ISSUE THREAD

**Issue by netgeppo** [Kodo-kakaku/luci-app-gpoint#17]
Ciao
I have a GL.iNet GL-X750 with (openwrt-19.07 branch (git-21.189.23240-7b931da) / OpenWrt 19.07.8 r11364-ef56c85848)
I try to install luci-app-gpoint_2.0.0_all.ipk but I have a problem
Installing luci-app-gpoint (2.0.0) to root...
Collected errors:
  * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-gpoint:
  * lua-bit32
  * opkg_install_cmd: Cannot install package luci-app-gpoint.
Unfortunately I can't find lua-bit32
Is it maybe an openwrt version issue?
How can I fix?
Thank you

**Comment by Kodo-kakaku** [comment]
**Hi @netgeppo !!!**
I ran into this problem because I had the same router))) In fact, I have no idea why this package was not included in the 19th branch and has been supported since the 21st... 
How can I help you fix this:
- Upgrade to the version starting from 21, and then everything will work... but that would be too easy, wouldn't it?)))
- If you download the .ipk file from the repository (for example, from [here](https://downloads.openwrt.org/releases/21.02.0/packages/mipsel_24kc/packages/)) and install everything will work!
- Add a link to 21 repositories in opkg, and then the package manager will find lua-bit32!
**I will be waiting for your feedback and thank you for your interest in the project!!!)**

**Comment by netgeppo** [comment]
Hi Kodo-kakaku 
Thanks for your help, unfortunately I'm not very capable, I have to figure out how to upgrade to version 21 and then install gpoint ... without losing router functionality,
Thank you very much

**Comment by netgeppo** [comment]
Hi Kodo-kakaku
Good! I upgraded and installed gpoint
Perfect installation
How can I check if my gps (U-Blocx 7) is working?
What commands can I give? to verify?
Thank you

**Comment by netgeppo** [comment]
Ok !!...
lsusb
Bus 001 Device 004: ID 2c7c:0306 Quectel EP06-E
Bus 001 Device 003: ID 05e3:0752 Generic USB Storage
Bus 001 Device 007: ID 1546:01a7 u-blox AG - www.u-blox.com u-blox 7 - GPS/GNSS Receiver
Bus 001 Device 002: ID 05e3:0618  USB2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux 5.10.146 ehci_hcd EHCI Host Controller

root@GL-X750:~# ls -l /dev/ttyACM0
crw-rw----    1 root     dialout   166,   0 Jan 27 12:04 /dev/ttyACM0
root@GL-X750:~# 

root@GL-X750:~# sudo cat /dev/ttyACM0

work...!

**Comment by netgeppo** [comment]
Now .... I would like to send this data to my small traccar server ....
Osman protocol
how can I do?

**Comment by Kodo-kakaku** [comment]
**Hi @netgeppo!**
I am very glad that you were able to launch the app! As for the server, to be honest, I have never used Traccar, but they have the [OsmAnd](https://www.traccar.org/osmand/) protocol implemented by them. 

You will need to: 
- activate the server (Enable server:) 
- enable Traccar Client
- set the time for sending messages (I recommend 1 message in 10 seconds, for example) 
- in the address column you need to specify the IP or DNS of your remote server (I hope you have a static one) 
- in the port column write 5055 (this is the protocol port on the server) 
- specify the ID of your device, this can be done in the login field, (you can use any id that does not match other devices, for example 12345)

**_After changing the settings, the device will start sending data to your server. Please write about your results, it is very important to me))_**
