### ISSUE TITLE
Change the default map zoom to World instead of Europe

### ISSUE THREAD

**Issue by PR-NCE** [Kodo-kakaku/luci-app-gpoint#28]
I am located in the USA and when I use the overview page, it shows me Europe and part of Asia, when it locates me, it shows a weird animation trying to zoom in from Europe going into the Atlantic ocean and then suddenly ends up on my location, I think changing the default map location to overview of all continents can solve this problem.

@Kodo-kakaku you asked me before for feedback: I tested luci-app-gpoint v.2.5.7 with sierra EM7565 and EM7455 and it works flawlessly. great job!

**Comment by Kodo-kakaku** [comment]
Hello @PR-NCE !
The animation is actually a screensaver at the moment of searching for coordinates by your modem. In the near future I will make changes in which I will change the scale of the map so that the default screen saver is the world, stay tuned! 

Thank you for your feedback and provided information about the operation of modems, this is important for the project!

**Comment by Kodo-kakaku** [comment]
Hi @PR-NCE !
I fixed the animation of the interface in version 2.5.8, now there will be no sense of flight and, as you asked, I zoomed out so that the United States of America falls on the initial screensaver! Thank you for making the project better!
